server:
  port: 9005
spring:
  application:
    name: report-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

services:
  customer: http://localhost:9001/api/v1
  bankaccount: http://localhost:9002/api/v1
  credit: http://localhost:9003/api/v1
  transaction: http://localhost:9004/api/v1
  report: http://localhost:9005/api/v1
  card: http://localhost:9006/api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
